[package]
name = "flow-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
anyhow = "1.0"
tracing.workspace = true
tonic-health = "0.11"
pt = { path = "../pt" }
catalog = { path = "../catalog" }
bcrypt = "0.15.1"
base64 = "0.22.1"
