name: Lint UI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: [ui/**]

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run UI linters
    strategy:
      matrix:
        runner: [ubuntu-24.04]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: generate or hydrate protos
        uses: ./.github/actions/genprotos

      - name: Install Node.js dependencies
        working-directory: ui
        run: npm ci

      - name: lint
        uses: wearerequired/lint-action@548d8a7c4b04d3553d32ed5b6e91eb171e10e7bb # v2
        with:
          eslint: true
          prettier: true
          eslint_dir: ui
          prettier_dir: ui
          eslint_args: "--max-warnings 0"
          eslint_extensions: js,ts,jsx,tsx
          prettier_extensions: js,ts,jsx,tsx,json
